spring:
  profiles:
    active: types,tools
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-message: always
logging:
  level:
    org.springframework.web: INFO